name: Stockwatch Cron Job

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes

permissions:
  contents: write

jobs:
  run-every-5-minutes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make the script executable
        run: chmod +x get_stock_prices.sh

      - name: Run get_stock_prices.sh
        run: ./get_stock_prices.sh

      - name: Set up counter file if not exists
        run: |
          if [ ! -f counter.txt ]; then
            echo 0 > counter.txt
          fi

      - name: Increment counter
        run: |
          count=$(cat counter.txt)
          count=$((count + 1))
          echo $count > counter.txt
          echo "Current count: $count"

      - name: Commit and push files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add counter.txt
          git add stock_prices.json
          git commit -m "Increment counter to $count"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}