name: Run get_stock_prices.sh on demand

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make the script executable
        run: chmod +x get_stock_prices.sh

      - name: Run get_stock_prices.sh
        run: ./get_stock_prices.sh

      - name: Commit and push files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stock_prices.json
          git commit -m "Updated stock_prices.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}