name: Run get_stock_prices.sh on demand

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run get_stock_prices.sh
        run: ./get_stock_prices.sh